spring:
  datasource:
    url: ${LIFEOS_DB_URL}
    username: ${LIFEOS_DB_USERNAME}
    password: ${LIFEOS_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  level:
    root: INFO
    com.adgaiz.lifeos: INFO
  structured:
    format:
      console: logstash
